### ISSUE TITLE
Sessions db got corrupted?

### ISSUE THREAD

**Issue by orta** [artsy/team-navigator#74]
Likely due to the scheduled tasks, if I had to guess.

```
2017-02-25T16:38:51.824450+00:00 app[web.1]:
2017-02-25T16:38:51.824519+00:00 app[web.1]:   koa-generic-session set error: server instance pool was destroyed
2017-02-25T16:38:51.824521+00:00 app[web.1]:       at Function.MongoError.create (/app/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
2017-02-25T16:38:51.824522+00:00 app[web.1]:       at basicWriteValidations (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:447:51)
2017-02-25T16:38:51.824523+00:00 app[web.1]:       at Server.update (/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:560:16)
2017-02-25T16:38:51.824523+00:00 app[web.1]:       at Server.update (/app/node_modules/mongodb/lib/server.js:390:17)
2017-02-25T16:38:51.824524+00:00 app[web.1]:       at updateDocuments (/app/node_modules/mongodb/lib/collection.js:1044:19)
2017-02-25T16:38:51.824525+00:00 app[web.1]:       at Collection.update (/app/node_modules/mongodb/lib/collection.js:1083:44)
2017-02-25T16:38:51.824525+00:00 app[web.1]:       at Object.<anonymous> (/app/node_modules/thunkify/index.js:43:12)
2017-02-25T16:38:51.824529+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:103:7)
2017-02-25T16:38:51.824526+00:00 app[web.1]:       at /app/node_modules/co/index.js:136:8
2017-02-25T16:38:51.824527+00:00 app[web.1]:       at Object.thunkToPromise (/app/node_modules/co/index.js:135:10)
2017-02-25T16:38:51.824527+00:00 app[web.1]:       at Object.toPromise (/app/node_modules/co/index.js:119:55)
2017-02-25T16:38:51.824529+00:00 app[web.1]:       at onFulfilled (/app/node_modules/co/index.js:69:7)
2017-02-25T16:38:51.824557+00:00 app[web.1]:
2017-02-25T16:38:51.824528+00:00 app[web.1]:       at next (/app/node_modules/co/index.js:99:29)
2017-02-25T16:42:06.168275+00:00 heroku[router]: at=info method=GET path="/" host=team.artsy.net request_id=f1de1c25-5877-43f7-9131-184f1224bc13 fwd="82.30.161.174" dyno=web.1 connect=0ms service=9ms status=500 bytes=176
2017-02-25T16:42:06.152981+00:00 app[web.1]:
2017-02-25T16:42:06.153035+00:00 app[web.1]:       at nextFunction (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:540:25)
2017-02-25T16:42:06.153033+00:00 app[web.1]:   koa-generic-session get error: Topology was destroyed
2017-02-25T16:42:06.153035+00:00 app[web.1]:       at Cursor.next [as _next] (/app/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:692:3)
2017-02-25T16:42:06.153036+00:00 app[web.1]:       at nextObject (/app/node_modules/mongodb/lib/cursor.js:671:8)
2017-02-25T16:42:06.153036+00:00 app[web.1]:       at Cursor.next (/app/node_modules/mongodb/lib/cursor.js:261:12)
2017-02-25T16:42:06.153037+00:00 app[web.1]:       at findOne (/app/node_modules/mongodb/lib/collection.js:1404:10)
2017-02-25T16:42:06.153040+00:00 app[web.1]:       at Collection.findOne (/app/node_modules/mongodb/lib/collection.js:1390:44)
2017-02-25T16:42:06.153041+00:00 app[web.1]:       at Object.<anonymous> (/app/node_modules/thunkify/index.js:43:12)
2017-02-25T16:42:06.153041+00:00 app[web.1]:       at /app/node_modules/co/index.js:136:8
2017-02-25T16:42:06.153042+00:00 app[web.1]:       at Object.thunkToPromise (/app/node_modules/co/index.js:135:10)
2017-02-25T16:42:06.153042+00:00 app[web.1]:       at Object.toPromise (/app/node_modules/co/index.js:119:55)
2017-02-25T16:42:06.153042+00:00 app[web.1]:       at next (/app/node_modules/co/index.js:99:29)
2017-02-25T16:42:06.153043+00:00 app[web.1]:       at onFulfilled (/app/node_modules/co/index.js:69:7)
2017-02-25T16:42:06.153043+00:00 app[web.1]:       at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by orta** [comment]
For now, I've made the schedulers echo instead of running their scripts.
